Class {
	#name : #SomeTonelTraitDefinition,
	#superclass : #SomeTonelDefinition,
	#instVars : [
		'name',
		'comment',
		'traitComposition',
		'classTraitComposition',
		'instanceVariables',
		'classInstanceVariables',
		'package',
		'tag',
		'category',
		'rawMetadata'
	],
	#category : #'GToolkit-VirtualMachine-SomeBindings-Tonel'
}

{ #category : #'as yet unclassified' }
SomeTonelTraitDefinition >> name [
	^ name
]
