Class {
	#name : #SomeTonelClassDefinition,
	#superclass : #SomeTonelDefinition,
	#instVars : [
		'name',
		'supeclass',
		'comment',
		'traitComposition',
		'classTraitComposition',
		'instanceVariables',
		'classVariables',
		'classInstanceVariables',
		'poolDictionaries',
		'package',
		'tag',
		'category',
		'typeName',
		'rawMetadata'
	],
	#category : #'GToolkit-VirtualMachine-SomeBindings-Tonel'
}

{ #category : #'as yet unclassified' }
SomeTonelClassDefinition >> name [
	^ name
]
